In [73]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes

In [74]:
X, y = load_diabetes()['data'], load_diabetes()['target']
X.shape, y.shape

((442, 10), (442,))

In [75]:
from sklearn.model_selection import train_test_split

In [76]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((353, 10), (353,), (89, 10), (89,))

In [77]:
class Mlr : 
    
    def __init__(self) : 
        self.coef_ = None
        self.intercept_ = None
        self.B = None
        
    def fit(self, X, Y) :
        row, col = X.shape
        X_final = np.hstack([np.ones([row,1]), X])
        # xt_x_invert = np.invert( np.dot( np.transpose( X_final ), X_final) ) 
        # xt_x_invert_xt = np.dot( xt_x_invert, np.transpose( X_final ) )
        
        self.B = np.linalg.inv(np.dot(X_final.T, X_final)).dot(X_final.T).dot(Y) 
        
    
    def predict(self, X) : 
        row, col = X.shape
        X_final = np.hstack([np.ones([row,1]), X])
        return np.dot(X_final, self.B)

In [78]:
mlr = Mlr()

In [79]:
np.ones([2,1])

array([[1.],
       [1.]])

In [80]:
mlr.fit(X_train, y_train)

In [81]:
mlr.B

array([ 151.88334521,   -9.16088483, -205.46225988,  516.68462383,
        340.62734108, -895.54360867,  561.21453306,  153.88478595,
        126.73431596,  861.12139955,   52.41982836])

In [82]:
y_pred_mlr = mlr.predict(X_test)
y_pred_mlr

array([154.1235067 , 204.81721599, 124.92988001, 106.09339576,
       258.53035681, 256.32953702, 118.75258786, 119.52147402,
       101.50717468, 190.54137158, 141.70360267, 172.51631204,
       174.34089304, 134.81184017, 294.13950798,  94.11403289,
       211.97052873, 156.49984762, 134.20709632, 119.62534726,
       148.88045343, 165.00378118, 151.09977307, 176.03719872,
       133.27651748, 221.29531227, 197.17482787,  96.15923158,
        50.26531577, 230.48342249, 242.06266394, 114.1153262 ,
        67.0785352 ,  94.53179042, 201.21593262, 167.05306138,
       159.87838519, 192.78601513, 114.49291816, 233.4825497 ,
       140.82309666, 121.06814332, 192.27431013, 191.13157307,
       179.1698153 , 148.35140027, 163.47610288, 276.81203359,
       100.17813072, 164.11265163, 255.81074398, 136.94979051,
       152.37507828, 107.92662528, 194.21661635,  77.35015426,
       118.50951725,  68.38527563, 154.29094022, 162.48905632,
       168.36590928, 156.8764705 ,  97.13958436, 238.17

In [83]:
y_test

array([ 73., 233.,  97., 111., 277., 341.,  64.,  68.,  65., 178., 142.,
        77., 244., 115., 258.,  87., 220.,  86.,  74., 132., 136., 220.,
        91., 235., 148., 317., 131.,  84.,  65., 217., 306.,  79., 158.,
        54., 123., 174., 237., 212., 179., 281., 187., 200.,  68., 163.,
       141., 202., 178., 242.,  47., 131., 243., 142., 200.,  89., 232.,
        55., 253., 128., 104., 184., 110., 198.,  81., 195., 150.,  63.,
       151., 233., 178.,  84., 237., 109., 131., 252., 200., 160., 200.,
        51., 111.,  77., 201.,  88.,  78., 243., 268.,  55., 270., 288.,
        91.])

In [84]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [85]:
r2_score(y_test, y_pred_mlr)

0.4399387660024642

In [86]:
lr = LinearRegression()

In [87]:
lr.fit(X_train, y_train)

LinearRegression()

In [88]:
y_pred_lr = lr.predict(X_test)
y_pred_lr

array([154.1235067 , 204.81721599, 124.92988001, 106.09339576,
       258.53035681, 256.32953702, 118.75258786, 119.52147402,
       101.50717468, 190.54137158, 141.70360267, 172.51631204,
       174.34089304, 134.81184017, 294.13950798,  94.11403289,
       211.97052873, 156.49984762, 134.20709632, 119.62534726,
       148.88045343, 165.00378118, 151.09977307, 176.03719872,
       133.27651748, 221.29531227, 197.17482787,  96.15923158,
        50.26531577, 230.48342249, 242.06266394, 114.1153262 ,
        67.0785352 ,  94.53179042, 201.21593262, 167.05306138,
       159.87838519, 192.78601513, 114.49291816, 233.4825497 ,
       140.82309666, 121.06814332, 192.27431013, 191.13157307,
       179.1698153 , 148.35140027, 163.47610288, 276.81203359,
       100.17813072, 164.11265163, 255.81074398, 136.94979051,
       152.37507828, 107.92662528, 194.21661635,  77.35015426,
       118.50951725,  68.38527563, 154.29094022, 162.48905632,
       168.36590928, 156.8764705 ,  97.13958436, 238.17

In [89]:
r2_score(y_test, y_pred_lr), r2_score(y_test, y_pred_mlr)

(0.4399387660024645, 0.4399387660024642)